namespace WindosRecorder.Services;

public static class LanguageCatalog
{
    public const string Chinese = "zh";
    public const string English = "en";

    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
    {
        [Chinese] = new Dictionary<string, string>
        {
            ["AppTitle"] = "WINDOS 高清录屏器",
            ["HeroTitle"] = "WINDOS 高清录屏器",
            ["HeroSubtitle"] = "支持全屏录制、窗口录制、麦克风同步录音，以及单独音频录制的便携版应用。",
            ["SettingsTitle"] = "录制设置",
            ["ModeLabel"] = "录制模式",
            ["ModeFullScreen"] = "全屏录制",
            ["ModeWindow"] = "窗口录制",
            ["ModeAudioOnly"] = "单独录音",
            ["MicrophoneLabel"] = "麦克风",
            ["SystemAudioVolume"] = "系统声音音量",
            ["MicrophoneVolume"] = "麦克风音量",
            ["MicrophoneBoost"] = "麦克风放大",
            ["RecordingName"] = "记录名称",
            ["RecordingNameHint"] = "输入保存名称，程序会自动在后面加上时间",
            ["FilePreview"] = "最终文件预览",
            ["WindowLabel"] = "目标窗口",
            ["ChooseWindowButton"] = "选择窗口",
            ["ChooseWindowPlaceholder"] = "点击右侧按钮选择窗口",
            ["ChooseWindowDialogTitle"] = "选择窗口",
            ["ChooseWindowDialogSubtitle"] = "请选择要录制的目标窗口",
            ["RefreshWindows"] = "刷新窗口",
            ["IncludeSystemAudio"] = "录制系统声音",
            ["IncludeMic"] = "录制视频时同时录制麦克风",
            ["FrameRate"] = "帧率",
            ["Resolution"] = "分辨率",
            ["Bitrate"] = "视频码率 (kbps)",
            ["SaveTitle"] = "保存位置",
            ["SaveDescription"] = "在这里设置默认保存目录。每次开始录制时，程序会自动按时间生成文件名。",
            ["ChooseFolder"] = "选择文件夹",
            ["OpenSaveFolder"] = "打开视频文件夹",
            ["SupportAuthorTitle"] = "支持作者",
            ["SupportAuthorSubtitle"] = "如果觉得好用，欢迎支持 long-X 继续更新",
            ["SupportAuthorMessage"] = "如果 X 录屏器帮到了你，欢迎自愿支持作者。二维码稍后会添加到这里。",
            ["SupportPrimary"] = "微信",
            ["SupportSecondary"] = "支付宝",
            ["SupportQrPlaceholder"] = "二维码待添加",
            ["SupportPrimaryDetail"] = "二维码待添加",
            ["SupportSecondaryDetail"] = "二维码待添加",
            ["AuthorLabel"] = "作者：long-X",
            ["SystemAudioCardTitle"] = "系统声音",
            ["SystemAudioDescription"] = "录屏时是否同时录入系统播放的声音",
            ["TipsTitle"] = "录制提醒",
            ["TipsLineOne"] = "开始录制后会先显示 5 秒倒计时，随后主界面自动缩小为录制控制窗。",
            ["TipsLineTwo"] = "录制过程中可以在小窗口里暂停、停止、调节系统声音和麦克风音量。",
            ["RecordingHint"] = "录制过程中，这个控制窗会尽量排除在录屏画面之外。",
            ["BitrateHint"] = "当前分辨率推荐码率：{0} kbps，你也可以自行调整。",
            ["StorageEstimate"] = "预计每分钟约占用 {0}，当前保存分区 {2} 剩余 {3}，最长可录约 {1}。",
            ["StorageEstimateUnavailable"] = "暂时无法计算存储占用，请先选择有效的保存路径。",
            ["StorageEstimateInvalidBitrate"] = "请输入有效码率后查看每分钟占用和最长可录时间。",
            ["StorageEstimateAudioOnly"] = "单独录音模式输出 WAV，暂不按视频码率估算容量。",
            ["NextFile"] = "下一个文件",
            ["Status"] = "状态",
            ["Ready"] = "准备就绪",
            ["LoadingDevices"] = "正在加载录制设备和窗口列表…",
            ["CountdownTitle"] = "即将开始录制",
            ["RecordingMiniTitle"] = "正在录制",
            ["Pause"] = "暂停",
            ["Resume"] = "继续",
            ["Start"] = "开始录制",
            ["Stop"] = "停止录制",
            ["ModeAudio"] = "当前为仅音频录制模式",
            ["ModeVideo"] = "当前为视频录制模式",
            ["ChooseSaveFolderFirst"] = "请先选择保存文件夹。",
            ["ChooseAudioSource"] = "请至少开启一个音频来源，或切换到不需要录音的模式。",
            ["NoMicrophone"] = "没有检测到可用的麦克风设备。",
            ["ChooseWindow"] = "请选择要录制的目标窗口。",
            ["RecordingAudio"] = "正在录制音频：{0}",
            ["RecordingVideo"] = "正在录制视频：{0}",
            ["StartFailed"] = "启动失败",
            ["Stopped"] = "录制已停止",
            ["NoWindowFound"] = "没有找到可录制的窗口",
            ["WindowRefreshed"] = "窗口列表已刷新，共找到 {0} 个窗口",
            ["ChooseSaveLocation"] = "请选择录制文件保存位置",
            ["SaveUpdated"] = "保存位置已更新",
            ["ReleaseDependencyFailed"] = "启动时释放录屏组件失败：{0}",
            ["LanguageTitle"] = "选择语言",
            ["LanguageSubtitle"] = "请选择界面语言",
            ["LanguageChinese"] = "中文",
            ["LanguageEnglish"] = "English",
            ["LanguageConfirm"] = "确定",
            ["LanguageCancel"] = "取消",
            ["StartupTimeoutMessage"] = "程序在 10 秒内未能完成启动。\n可能是录屏组件初始化失败或当前系统环境不兼容。\n请查看同目录下的 app-debug.log 获取更多信息。",
            ["RecordingFinished"] = "录制完成：{0}",
            ["RecordingFailed"] = "录制失败：{0}",
            ["RecordingStatus"] = "录制状态：{0}",
            ["StartupFailed"] = "启动失败",
            ["AutomationWindowNotFound"] = "没有找到标题包含“{0}”的窗口。",
            ["AutomationStarted"] = "自动录制已开始：{0}",
            ["AutomationFinished"] = "自动录制已完成：{0}"
        },
        [English] = new Dictionary<string, string>
        {
            ["AppTitle"] = "WINDOS Recorder",
            ["HeroTitle"] = "WINDOS Recorder",
            ["HeroSubtitle"] = "Portable recorder for fullscreen capture, window capture, microphone recording, and audio-only recording.",
            ["SettingsTitle"] = "Recording Settings",
            ["ModeLabel"] = "Capture Mode",
            ["ModeFullScreen"] = "Fullscreen",
            ["ModeWindow"] = "Window",
            ["ModeAudioOnly"] = "Audio Only",
            ["MicrophoneLabel"] = "Microphone",
            ["SystemAudioVolume"] = "System Audio Volume",
            ["MicrophoneVolume"] = "Microphone Volume",
            ["MicrophoneBoost"] = "Mic Boost",
            ["RecordingName"] = "Recording Name",
            ["RecordingNameHint"] = "Enter a save name. The app will append a timestamp automatically.",
            ["FilePreview"] = "Final File Preview",
            ["WindowLabel"] = "Target Window",
            ["ChooseWindowButton"] = "Choose Window",
            ["ChooseWindowPlaceholder"] = "Choose a target window",
            ["ChooseWindowDialogTitle"] = "Choose Window",
            ["ChooseWindowDialogSubtitle"] = "Pick the window you want to record",
            ["RefreshWindows"] = "Refresh Windows",
            ["IncludeSystemAudio"] = "Record system audio",
            ["IncludeMic"] = "Record microphone while capturing video",
            ["FrameRate"] = "Frame Rate",
            ["Resolution"] = "Resolution",
            ["Bitrate"] = "Video Bitrate (kbps)",
            ["SaveTitle"] = "Save Location",
            ["SaveDescription"] = "Choose the default folder here. The app will create a timestamped filename for each recording.",
            ["ChooseFolder"] = "Choose Folder",
            ["OpenSaveFolder"] = "Open Video Folder",
            ["SupportAuthorTitle"] = "Support Author",
            ["SupportAuthorSubtitle"] = "If X Recorder helps, you can support long-X",
            ["SupportAuthorMessage"] = "If X Recorder is useful to you, you can voluntarily support the author. QR codes will be added here later.",
            ["SupportPrimary"] = "PayPal",
            ["SupportSecondary"] = "Ko-fi",
            ["SupportQrPlaceholder"] = "Support link coming soon",
            ["SupportPrimaryDetail"] = "PayPal email:\nszxwl2@gmail.com",
            ["SupportSecondaryDetail"] = "Coming soon",
            ["AuthorLabel"] = "Author: long-X",
            ["SystemAudioCardTitle"] = "System Audio",
            ["SystemAudioDescription"] = "Choose whether to capture audio currently playing on the system.",
            ["TipsTitle"] = "Recording Tips",
            ["TipsLineOne"] = "Recording starts with a 5-second countdown, then the main window shrinks into the control panel.",
            ["TipsLineTwo"] = "During recording, you can pause, stop, and adjust system and microphone volume in the floating window.",
            ["RecordingHint"] = "During recording, this control panel will try to stay out of the captured video.",
            ["BitrateHint"] = "Recommended bitrate for this resolution: {0} kbps. You can adjust it manually.",
            ["StorageEstimate"] = "Estimated usage is about {0} per minute. Drive {2} has {3} free, so the maximum recording time is about {1}.",
            ["StorageEstimateUnavailable"] = "Storage estimation is unavailable until a valid save folder is selected.",
            ["StorageEstimateInvalidBitrate"] = "Enter a valid bitrate to calculate usage per minute and maximum recording time.",
            ["StorageEstimateAudioOnly"] = "Audio-only mode exports WAV, so video bitrate estimation is not used here.",
            ["NextFile"] = "Next File",
            ["Status"] = "Status",
            ["Ready"] = "Ready",
            ["LoadingDevices"] = "Loading recording devices and windows...",
            ["CountdownTitle"] = "Recording starts in",
            ["RecordingMiniTitle"] = "Recording",
            ["Pause"] = "Pause",
            ["Resume"] = "Resume",
            ["Start"] = "Start Recording",
            ["Stop"] = "Stop Recording",
            ["ModeAudio"] = "Audio-only mode is active",
            ["ModeVideo"] = "Video recording mode is active",
            ["ChooseSaveFolderFirst"] = "Please choose a save folder first.",
            ["ChooseAudioSource"] = "Please enable at least one audio source, or switch to a mode that does not require audio.",
            ["NoMicrophone"] = "No microphone device was detected.",
            ["ChooseWindow"] = "Please choose a target window to record.",
            ["RecordingAudio"] = "Recording audio: {0}",
            ["RecordingVideo"] = "Recording video: {0}",
            ["StartFailed"] = "Start Failed",
            ["Stopped"] = "Recording stopped",
            ["NoWindowFound"] = "No capturable window was found",
            ["WindowRefreshed"] = "Window list refreshed: {0} window(s) found",
            ["ChooseSaveLocation"] = "Choose where recordings should be saved",
            ["SaveUpdated"] = "Save location updated",
            ["ReleaseDependencyFailed"] = "Failed to extract the recording component on startup: {0}",
            ["LanguageTitle"] = "Select Language",
            ["LanguageSubtitle"] = "Choose the interface language",
            ["LanguageChinese"] = "中文",
            ["LanguageEnglish"] = "English",
            ["LanguageConfirm"] = "OK",
            ["LanguageCancel"] = "Cancel",
            ["StartupTimeoutMessage"] = "The app did not finish starting within 10 seconds.\nThe recording component may have failed to initialize, or this system may be incompatible.\nPlease check app-debug.log in the app folder for more details.",
            ["RecordingFinished"] = "Recording finished: {0}",
            ["RecordingFailed"] = "Recording failed: {0}",
            ["RecordingStatus"] = "Recorder status: {0}",
            ["StartupFailed"] = "Startup Failed",
            ["AutomationWindowNotFound"] = "No window with title containing \"{0}\" was found.",
            ["AutomationStarted"] = "Automation recording started: {0}",
            ["AutomationFinished"] = "Automation recording finished: {0}"
        }
    };

    public static string Normalize(string? language)
    {
        return language == English ? English : Chinese;
    }

    public static string Get(string language, string key)
    {
        var normalized = Normalize(language);
        return Strings[normalized].TryGetValue(key, out var value) ? value : key;
    }
}
